### ISSUE TITLE
unable to use it: [!] Error: ENOENT: no such file or directory, mkdir './static/g/'

### ISSUE THREAD

**Issue by jdgaravito** [matyunya/svelte-image#15]
I cant make it work, added `import image from "svelte-image";  `and then added the preprocess section to the rollup config file.

```
export default {
	input: 'src/main.js',
	output: {
		sourcemap: true,
		format: 'iife',
		name: 'app',
		file: 'public/bundle.js'
	},
	plugins: [
		svelte({
			// enable run-time checks when not in production
			dev: !production,
			// we'll extract any component CSS out into
			// a separate file — better for performance
			css: css => {
				css.write('public/bundle.css');
			},

			preprocess: {
				...image(),
			  }
		}),

```
then in the component i imported again:

`import Image from "svelte-image";`

and used in the html 

`<Image src="images/fuji.jpg"/> with a sample image called fuji.jpg>`

and i noticed sometimes in the docs you use image other Image.

tried to manually create such folders in public with no results. 

i see that your  index.js mentions `outputDir: "g/",`

and `function getOutPath(options, filename) {
  const dir = "./static/" + options.outputDir;
  return (outPath = path.resolve(dir, filename));
}`

log:
Error: ENOENT: no such file or directory, mkdir './static/g/'
    at Object.mkdirSync (fs.js:757:3)
    at init (/mnt/c/Users/jdgar/Github/Bitagora/bitagora_frontend/node_modules/svelte-image/index.js:173:8)
    at getPreprocessor (/mnt/c/Users/jdgar/Github/Bitagora/bitagora_frontend/node_modules/svelte-image/index.js:325:3)
    at Object.<anonymous> (/mnt/c/Users/jdgar/Github/Bitagora/bitagora_frontend/rollup.config.js:35:8)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.require.extensions..js (/mnt/c/Users/jdgar/Github/Bitagora/bitagora_frontend/node_modules/rollup/dist/bin/rollup:838:24)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "autobuild" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jdgaravito** [comment]
UPDATE: I manage to create the folder (it should create the folder  automatically or mention this on the readme), in the root of svelte app and now it seems to progress but now i have other error:

[!] (plugin svelte) TypeError: Cannot read property 'value' of undefined
node_modules/svelte-image/src/Image.svelte
TypeError: Cannot read property 'value' of undefined
    at getProp (/mnt/c/Users/jdgar/Github/Bitagora/bitagora_frontend/node_modules/svelte-image/index.js:69:52)    
    at getPathname (/mnt/c/Users/jdgar/Github/Bitagora/bitagora_frontend/node_modules/svelte-image/index.js:83:19)
    at replaceInImg (/mnt/c/Users/jdgar/Github/Bitagora/bitagora_frontend/node_modules/svelte-image/index.js:267:38)

**Comment by matyunya** [comment]
Honestly I never tried it without Sapper. Please share if manage to get it to work with Svelte only.
